## ??????????????????
#key1: java
## ???????
##key2:java
#
#
## ???
#String:
#  value: hello
#
## ????true?false
#boolean:
#  value1: true
#  value2: false
#
## ????????????????????key?????
#int:
#  value: 10
#
## ??????????????????????key?????
#float:
#  value: 3.14159
#
## ~ ??null,???????? ~ ???????key?????
#null:
#  value: ~
#
## "" ????
## '' ??????????
## ?????????????????????????????????????????
#empty:
#  value1: ''
#  value2: ""
#  value3:
#
#
#
#
#
#
kaptcha:
  image:
    width: 100
    height: 40
  textproducer:
    font:
      size: 24
  items:
  # admin captcha
    admin:
      path: /admin/captcha
      session:
        key: ADMIN_KAPTCHA_SESSION_KEY
        date: ADMIN_KAPTCHA_SESSION_DATE
#server:
#  tomcat:
#    remoteip:
#      internal-proxies:
