sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tRrowseRixd7JX8phzU
    access-key-secret: rD1H9iGoGXZIm65w9YDRbcl9Bqoeci
    bucket-name: quwuyou-1
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
  wechat:
    appid: wxf0566898bf059ce9
    secret: 282e7fdce84676733f44728043d80889
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl:
